### ISSUE TITLE
Confusion about the code implementation when solving C_init

### ISSUE THREAD

**Issue by Yiveen** [flrneha/ElasticBasisForSpectralMatching#2]
Hello! Thanks so much for your detailed and clear code implementation for the theory in the paper. But I have one confusion when we solve the `C_init` in the `solver.py`:
```
C_init = np.linalg.lstsq(np.kron(G, sqrtA), np.reshape(sqrtA.dot(F.T), (-1), order='F'), rcond=None)[0]
C_init = np.reshape(C_init, (self.kmin, self.kmin), order='F')
```
I can find the corresponding derivation from formula (13) in your paper, namely:
![1702249842123](https://github.com/flrneha/ElasticBasisForSpectralMatching/assets/98336036/c6d9fa67-481a-4828-9062-044ca5a20b81)
Although this formula aims to solve the correspondence map, if we already know the initial correspondence relationship between ei and ej, we can treat this formula as solving the optimization of functional map C.

But I am confused how I can deduce `F.T` from Φ<sub>1,k</sub><sup>+</sup> M<sub>1</sub><sup>-1</sup>e<sub>j</sub> (I take the latter one as an example)? Because I have tried to deduce that these two items are equal, but I failed. Because I will always get additional M<sub>2,k</sub> term from Φ<sub>1,k</sub><sup>+</sup> M<sub>1</sub><sup>-1</sup>e<sub>j</sub>.

Could you help me solve this problem? Thank you so much for your attention and participation.

**Comment by flrneha** [comment]
Dear @Yiveen 
to compute `C_init` we use the minimization
![formula(15)](https://github.com/flrneha/ElasticBasisForSpectralMatching/assets/73665649/ffb10be6-d7ec-4fcf-b3b4-dba83b1d6c44)
To solve the least square problem, we make use of a vectorized formulation. With the notation from the code this results in the least square problem $\Vert G \otimes \sqrt{M_{1,k}} \text{vec}(C) - \text{vec}(\sqrt{M_{1,k}} F^T)\Vert^2$ with `sqrtA` $=\sqrt{M_{1,k}}$.
I hope this answers your question!

**Comment by Yiveen** [comment]
Thanks so much for your quick and detailed answer! I have read formula (15) in the paper, but I am mainly confused with the relationship between formula(13) and formula(15). Although the form of these two formulas is different, I assume (15) is derived from (13). Because we cannot explicitly see sqrt(M1,k) in formula(15). 

Could you help me solve this confusion?Thanks!

**Comment by flrneha** [comment]
Ah sorry, now I think I got your question.
Indeed, you're right, the procedure for initialization with landmarks is a slightly different objective.
Another alternative could be to create a sparse point correspondence just given by the landmark correspondences and compute a functional map by projecting to the subspaces.

**Comment by Yiveen** [comment]
Thanks! So for the another alternative way you mean the another interpretation for the formula (13)? 

> Another alternative could be to create a sparse point correspondence just given by the landmark correspondences and compute a functional map by projecting to the subspaces.

But I still want to know how can I get formula(15) from (13), or you mean formula (13) and formula (15) don't have some direct relationship? Because I can get the LB formula from (14), but I cannot derive (15)from (13).
![图片](https://github.com/flrneha/ElasticBasisForSpectralMatching/assets/98336036/813e1640-2e58-45c9-81c6-83179ae8e9a3)

**Comment by flrneha** [comment]
(15) and (13) don't have a direct relationship, since the objective for initialization is slightly different.

If you search for some way to use (13) as an initialization you can build a similar initialization using (13) and a sparse correspondence but we haven't done so in our paper

**Comment by Yiveen** [comment]
Thank you immensely for your patient and detailed response! I'm now curious about the derivation of formula (15). Is it a form of definition analogous to the LB method, or does it stem from another formula? I didn't find any derivation in the paper.

Moreover, once we've derived formula (15), how do we derive the code formula involving sqrt(M1,k)?

Thank you in advance for your help and clarification!

**Comment by flrneha** [comment]
Formula (15) solves the least square problem of aligning the values of basis functions at the given landmark positions without including any additional regularization. There is no further derivation to it.
The weight `sqrt(M1,k) ` stems from the reformulation of the Hilbert-Schmidt norm to the Euclidean norm used for computation as mentioned in my first response. You can also have a look at our supplementary material for some general statements that hold for this norm.

**Comment by Yiveen** [comment]
I've grasped it! After reviewing the supplementary material, I've discovered how to derive the code formulation for (15). Your invaluable support has been instrumental in this breakthrough. Thank you immensely for your guidance. Have a nice day! :)
